enum MpegVersionLayer
{
    Mpeg25_Layer3 = 0x1,
    Mpeg25_Layer2 = 0x2,
    Mpeg25_Layer1 = 0x3,
    Mpeg2_Layer3 = 0x9,
    Mpeg2_Layer2 = 0xA,
    Mpeg2_Layer1 = 0xB,
    Mpeg1_Layer3 = 0xD,
    Mpeg1_Layer2 = 0xE,
    Mpeg1_Layer1 = 0xF,
};

enum MpegChannelModes
{
    MpegChannel_Stereo,
    MpegChannel_JointStereo,
    MpegChannel_DualChannel,
    MpegChannel_SingleChannel,
};

enum MpegChannelExtension12
{
    MpegChannelExt12_Band4To31,
    MpegChannelExt12_Band8To31,
    MpegChannelExt12_Band12To31,
    MpegChannelExt12_Band16To31,
};

enum MpegChannelExtension3
{
    MpegChannelExt3_None,
    MpegChannelExt3_Intensity,
    MpegChannelExt3_MidSide,
    MpegChannelExt3_IntensityMidSide,
};

enum MpegEmphasis
{
    MpegEmphasis_None,
    MpegEmphasis_50_15ms,
    MpegEmphasis_Reserved,
    MpegEmphasis_CCIT_J17,
};

global u16 gMPEGBitRates[] =
{
    0, 32, 64, 96, 128, 160, 192, 224, 256, 288, 320, 352, 384, 416, 448, U16_MAX,
    0, 32, 48, 56,  64,  80,  96, 112, 128, 160, 192, 224, 256, 320, 384, U16_MAX,
    0, 32, 40, 48,  56,  64,  80,  96, 112, 128, 160, 192, 224, 256, 320, U16_MAX,
    0, 32, 48, 56,  64,  80,  96, 112, 128, 144, 160, 176, 192, 224, 256, U16_MAX,
    0,  8, 16, 24,  32,  40,  48,  56,  64,  80,  96, 112, 128, 144, 160, U16_MAX,
};

global u32 gMPEGSampleRates[] =
{
    44100, 48000, 32000, U32_MAX,
    22050, 24000, 16000, U32_MAX,
    11025, 12000,  8000, U32_MAX,
};

// NOTE(michiel): ID3v1/ID3v1.1
global String gID3v1Genres[256] =
{
    [0] = static_string("Blues"),
    [1] = static_string("Classic Rock"),
    [2] = static_string("Country"),
    [3] = static_string("Dance"),
    [4] = static_string("Disco"),
    [5] = static_string("Funk"),
    [6] = static_string("Grunge"),
    [7] = static_string("Hip-Hop"),
    [8] = static_string("Jazz"),
    [9] = static_string("Metal"),
    [10] = static_string("New Age"),
    [11] = static_string("Oldies"),
    [12] = static_string("Other"),
    [13] = static_string("Pop"),
    [14] = static_string("R&B"),
    [15] = static_string("Rap"),
    [16] = static_string("Reggae"),
    [17] = static_string("Rock"),
    [18] = static_string("Techno"),
    [19] = static_string("Industrial"),
    [20] = static_string("Alternative"),
    [21] = static_string("Ska"),
    [22] = static_string("Death Metal"),
    [23] = static_string("Pranks"),
    [24] = static_string("Soundtrack"),
    [25] = static_string("Euro-Techno"),
    [26] = static_string("Ambient"),
    [27] = static_string("Trip-Hop"),
    [28] = static_string("Vocal"),
    [29] = static_string("Jazz+Funk"),
    [30] = static_string("Fusion"),
    [31] = static_string("Trance"),
    [32] = static_string("Classical"),
    [33] = static_string("Instrumental"),
    [34] = static_string("Acid"),
    [35] = static_string("House"),
    [36] = static_string("Game"),
    [37] = static_string("Sound Clip"),
    [38] = static_string("Gospel"),
    [39] = static_string("Noise"),
    [40] = static_string("AlternRock"),
    [41] = static_string("Bass"),
    [42] = static_string("Soul"),
    [43] = static_string("Punk"),
    [44] = static_string("Space"),
    [45] = static_string("Meditative"),
    [46] = static_string("Instrumental Pop"),
    [47] = static_string("Instrumental Rock"),
    [48] = static_string("Ethnic"),
    [49] = static_string("Gothic"),
    [50] = static_string("Darkwave"),
    [51] = static_string("Techno-Industrial"),
    [52] = static_string("Electronic"),
    [53] = static_string("Pop-Folk"),
    [54] = static_string("Eurodance"),
    [55] = static_string("Dream"),
    [56] = static_string("Southern Rock"),
    [57] = static_string("Comedy"),
    [58] = static_string("Cult"),
    [59] = static_string("Gangsta"),
    [60] = static_string("Top 40"),
    [61] = static_string("Christian Rap"),
    [62] = static_string("Pop/Funk"),
    [63] = static_string("Jungle"),
    [64] = static_string("Native American"),
    [65] = static_string("Cabaret"),
    [66] = static_string("New Wave"),
    [67] = static_string("Psychadelic"),
    [68] = static_string("Rave"),
    [69] = static_string("Showtunes"),
    [70] = static_string("Trailer"),
    [71] = static_string("Lo-Fi"),
    [72] = static_string("Tribal"),
    [73] = static_string("Acid Punk"),
    [74] = static_string("Acid Jazz"),
    [75] = static_string("Polka"),
    [76] = static_string("Retro"),
    [77] = static_string("Musical"),
    [78] = static_string("Rock & Roll"),
    [79] = static_string("Hard Rock"),
    [80] = static_string("Folk"),
    [81] = static_string("Folk-Rock"),
    [82] = static_string("National Folk"),
    [83] = static_string("Swing"),
    [84] = static_string("Fast Fusion"),
    [85] = static_string("Bebob"),
    [86] = static_string("Latin"),
    [87] = static_string("Revival"),
    [88] = static_string("Celtic"),
    [89] = static_string("Bluegrass"),
    [90] = static_string("Avantgarde"),
    [91] = static_string("Gothic Rock"),
    [92] = static_string("Progressive Rock"),
    [93] = static_string("Psychedelic Rock"),
    [94] = static_string("Symphonic Rock"),
    [95] = static_string("Slow Rock"),
    [96] = static_string("Big Band"),
    [97] = static_string("Chorus"),
    [98] = static_string("Easy Listening"),
    [99] = static_string("Acoustic"),
    [100] = static_string("Humour"),
    [101] = static_string("Speech"),
    [102] = static_string("Chanson"),
    [103] = static_string("Opera"),
    [104] = static_string("Chamber Music"),
    [105] = static_string("Sonata"),
    [106] = static_string("Symphony"),
    [107] = static_string("Booty Brass"),
    [108] = static_string("Primus"),
    [109] = static_string("Porn Groove"),
    [110] = static_string("Satire"),
    [111] = static_string("Slow Jam"),
    [112] = static_string("Club"),
    [113] = static_string("Tango"),
    [114] = static_string("Samba"),
    [115] = static_string("Folklore"),
    [116] = static_string("Ballad"),
    [117] = static_string("Poweer Ballad"),
    [118] = static_string("Rhytmic Soul"),
    [119] = static_string("Freestyle"),
    [120] = static_string("Duet"),
    [121] = static_string("Punk Rock"),
    [122] = static_string("Drum Solo"),
    [123] = static_string("A Capela"),
    [124] = static_string("Euro-House"),
    [125] = static_string("Dance Hall"),
};
